import Head from 'next/head'
import Form from '../components/form'
import Nav from '../components/nav'
import Footer from '../components/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Formulário de Leads</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/favicon.png" />
      </Head>
      <Nav />
      <Form />
    </>
  )
}